/*
 * Salt Edge Payment Initiation API
 * API Reference for services
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@saltedge.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.utm.gitfit.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * CreatedPaymentResponseData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-21T15:13:42.040Z[GMT]")
public class CreatedPaymentResponseData {
  @SerializedName("id")
  private String id = null;

  @SerializedName("provider_code")
  private String providerCode = null;

  @SerializedName("provider_name")
  private String providerName = null;

  @SerializedName("customer_id")
  private String customerId = null;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  @SerializedName("updated_at")
  private OffsetDateTime updatedAt = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("template_identifier")
  private String templateIdentifier = null;

  @SerializedName("payment_attributes")
  private PaymentAttributes paymentAttributes = null;

  @SerializedName("stages")
  private List<Stage> stages = null;

  @SerializedName("custom_fields")
  private Object customFields = null;

  public CreatedPaymentResponseData id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CreatedPaymentResponseData providerCode(String providerCode) {
    this.providerCode = providerCode;
    return this;
  }

   /**
   * Get providerCode
   * @return providerCode
  **/
  @Schema(description = "")
  public String getProviderCode() {
    return providerCode;
  }

  public void setProviderCode(String providerCode) {
    this.providerCode = providerCode;
  }

  public CreatedPaymentResponseData providerName(String providerName) {
    this.providerName = providerName;
    return this;
  }

   /**
   * Get providerName
   * @return providerName
  **/
  @Schema(description = "")
  public String getProviderName() {
    return providerName;
  }

  public void setProviderName(String providerName) {
    this.providerName = providerName;
  }

  public CreatedPaymentResponseData customerId(String customerId) {
    this.customerId = customerId;
    return this;
  }

   /**
   * Get customerId
   * @return customerId
  **/
  @Schema(description = "")
  public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  public CreatedPaymentResponseData createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public CreatedPaymentResponseData updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @Schema(description = "")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public CreatedPaymentResponseData status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public CreatedPaymentResponseData templateIdentifier(String templateIdentifier) {
    this.templateIdentifier = templateIdentifier;
    return this;
  }

   /**
   * Get templateIdentifier
   * @return templateIdentifier
  **/
  @Schema(description = "")
  public String getTemplateIdentifier() {
    return templateIdentifier;
  }

  public void setTemplateIdentifier(String templateIdentifier) {
    this.templateIdentifier = templateIdentifier;
  }

  public CreatedPaymentResponseData paymentAttributes(PaymentAttributes paymentAttributes) {
    this.paymentAttributes = paymentAttributes;
    return this;
  }

   /**
   * Get paymentAttributes
   * @return paymentAttributes
  **/
  @Schema(description = "")
  public PaymentAttributes getPaymentAttributes() {
    return paymentAttributes;
  }

  public void setPaymentAttributes(PaymentAttributes paymentAttributes) {
    this.paymentAttributes = paymentAttributes;
  }

  public CreatedPaymentResponseData stages(List<Stage> stages) {
    this.stages = stages;
    return this;
  }

  public CreatedPaymentResponseData addStagesItem(Stage stagesItem) {
    if (this.stages == null) {
      this.stages = new ArrayList<Stage>();
    }
    this.stages.add(stagesItem);
    return this;
  }

   /**
   * Get stages
   * @return stages
  **/
  @Schema(description = "")
  public List<Stage> getStages() {
    return stages;
  }

  public void setStages(List<Stage> stages) {
    this.stages = stages;
  }

  public CreatedPaymentResponseData customFields(Object customFields) {
    this.customFields = customFields;
    return this;
  }

   /**
   * Get customFields
   * @return customFields
  **/
  @Schema(description = "")
  public Object getCustomFields() {
    return customFields;
  }

  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatedPaymentResponseData createdPaymentResponseData = (CreatedPaymentResponseData) o;
    return Objects.equals(this.id, createdPaymentResponseData.id) &&
        Objects.equals(this.providerCode, createdPaymentResponseData.providerCode) &&
        Objects.equals(this.providerName, createdPaymentResponseData.providerName) &&
        Objects.equals(this.customerId, createdPaymentResponseData.customerId) &&
        Objects.equals(this.createdAt, createdPaymentResponseData.createdAt) &&
        Objects.equals(this.updatedAt, createdPaymentResponseData.updatedAt) &&
        Objects.equals(this.status, createdPaymentResponseData.status) &&
        Objects.equals(this.templateIdentifier, createdPaymentResponseData.templateIdentifier) &&
        Objects.equals(this.paymentAttributes, createdPaymentResponseData.paymentAttributes) &&
        Objects.equals(this.stages, createdPaymentResponseData.stages) &&
        Objects.equals(this.customFields, createdPaymentResponseData.customFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, providerCode, providerName, customerId, createdAt, updatedAt, status, templateIdentifier, paymentAttributes, stages, customFields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatedPaymentResponseData {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    providerCode: ").append(toIndentedString(providerCode)).append("\n");
    sb.append("    providerName: ").append(toIndentedString(providerName)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    templateIdentifier: ").append(toIndentedString(templateIdentifier)).append("\n");
    sb.append("    paymentAttributes: ").append(toIndentedString(paymentAttributes)).append("\n");
    sb.append("    stages: ").append(toIndentedString(stages)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
