/*
 * Salt Edge Payment Initiation API
 * API Reference for services
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@saltedge.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.utm.gitfit.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * The following represents the object you get in the &#x60;extra&#x60; field of the payment field object.
 */
@Schema(description = "The following represents the object you get in the `extra` field of the payment field object.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-21T15:13:42.040Z[GMT]")
public class TemplatePaymentExtraField {
  @SerializedName("validation_regexp")
  private String validationRegexp = null;

  public TemplatePaymentExtraField validationRegexp(String validationRegexp) {
    this.validationRegexp = validationRegexp;
    return this;
  }

   /**
   * the regexp used for the payment field validation
   * @return validationRegexp
  **/
  @Schema(description = "the regexp used for the payment field validation")
  public String getValidationRegexp() {
    return validationRegexp;
  }

  public void setValidationRegexp(String validationRegexp) {
    this.validationRegexp = validationRegexp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplatePaymentExtraField templatePaymentExtraField = (TemplatePaymentExtraField) o;
    return Objects.equals(this.validationRegexp, templatePaymentExtraField.validationRegexp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(validationRegexp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplatePaymentExtraField {\n");
    
    sb.append("    validationRegexp: ").append(toIndentedString(validationRegexp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
