/*
 * Salt Edge Payment Initiation API
 * API Reference for services
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@saltedge.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.utm.gitfit.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * UnlockedCustomerResponseData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-21T15:13:42.040Z[GMT]")
public class UnlockedCustomerResponseData {
  @SerializedName("unlocked")
  private Boolean unlocked = true;

  @SerializedName("id")
  private Integer id = null;

  public UnlockedCustomerResponseData unlocked(Boolean unlocked) {
    this.unlocked = unlocked;
    return this;
  }

   /**
   * Get unlocked
   * @return unlocked
  **/
  @Schema(description = "")
  public Boolean isUnlocked() {
    return unlocked;
  }

  public void setUnlocked(Boolean unlocked) {
    this.unlocked = unlocked;
  }

  public UnlockedCustomerResponseData id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnlockedCustomerResponseData unlockedCustomerResponseData = (UnlockedCustomerResponseData) o;
    return Objects.equals(this.unlocked, unlockedCustomerResponseData.unlocked) &&
        Objects.equals(this.id, unlockedCustomerResponseData.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unlocked, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnlockedCustomerResponseData {\n");
    
    sb.append("    unlocked: ").append(toIndentedString(unlocked)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
