/*
 * Salt Edge Payment Initiation API
 * API Reference for services
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@saltedge.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.utm.gitfit.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * VisaPaymentAttributes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-21T15:13:42.040Z[GMT]")
public class VisaPaymentAttributes extends CommonPaymentAttributes implements PaymentAttributes {
  @SerializedName("currency_code")
  private String currencyCode = "USD";

  @SerializedName("debtor_PAN")
  private String debtorPAN = null;

  @SerializedName("creditor_pan")
  private String creditorPan = null;

  public VisaPaymentAttributes currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * The currency of the payment.
   * @return currencyCode
  **/
  @Schema(required = true, description = "The currency of the payment.")
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  public VisaPaymentAttributes debtorPAN(String debtorPAN) {
    this.debtorPAN = debtorPAN;
    return this;
  }

   /**
   * The debtor&#x27;s PAN
   * @return debtorPAN
  **/
  @Schema(description = "The debtor's PAN")
  public String getDebtorPAN() {
    return debtorPAN;
  }

  public void setDebtorPAN(String debtorPAN) {
    this.debtorPAN = debtorPAN;
  }

  public VisaPaymentAttributes creditorPan(String creditorPan) {
    this.creditorPan = creditorPan;
    return this;
  }

   /**
   * The creditor&#x27;s PAN
   * @return creditorPan
  **/
  @Schema(required = true, description = "The creditor's PAN")
  public String getCreditorPan() {
    return creditorPan;
  }

  public void setCreditorPan(String creditorPan) {
    this.creditorPan = creditorPan;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VisaPaymentAttributes visaPaymentAttributes = (VisaPaymentAttributes) o;
    return Objects.equals(this.currencyCode, visaPaymentAttributes.currencyCode) &&
        Objects.equals(this.debtorPAN, visaPaymentAttributes.debtorPAN) &&
        Objects.equals(this.creditorPan, visaPaymentAttributes.creditorPan) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currencyCode, debtorPAN, creditorPan, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VisaPaymentAttributes {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    debtorPAN: ").append(toIndentedString(debtorPAN)).append("\n");
    sb.append("    creditorPan: ").append(toIndentedString(creditorPan)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
