/*
 * Salt Edge Payment Initiation API
 * API Reference for services
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@saltedge.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.utm.gitfit.model.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Error
 */
@Schema(description = "Error")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-21T15:13:42.040Z[GMT]")
public class ApiError {
  @SerializedName("error_class")
  private String errorClass = null;

  @SerializedName("error_message")
  private String errorMessage = null;

  @SerializedName("request")
  private Object request = null;

  public ApiError errorClass(String errorClass) {
    this.errorClass = errorClass;
    return this;
  }

   /**
   * The class of the error.
   * @return errorClass
  **/
  @Schema(required = true, description = "The class of the error.")
  public String getErrorClass() {
    return errorClass;
  }

  public void setErrorClass(String errorClass) {
    this.errorClass = errorClass;
  }

  public ApiError errorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * A message describing the error.
   * @return errorMessage
  **/
  @Schema(required = true, description = "A message describing the error.")
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }

  public ApiError request(Object request) {
    this.request = request;
    return this;
  }

   /**
   * the body of the request that caused the error.
   * @return request
  **/
  @Schema(required = true, description = "the body of the request that caused the error.")
  public Object getRequest() {
    return request;
  }

  public void setRequest(Object request) {
    this.request = request;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiError apiError = (ApiError) o;
    return Objects.equals(this.errorClass, apiError.errorClass) &&
        Objects.equals(this.errorMessage, apiError.errorMessage) &&
        Objects.equals(this.request, apiError.request);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorClass, errorMessage, request);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiError {\n");
    
    sb.append("    errorClass: ").append(toIndentedString(errorClass)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
