/*
 * Salt Edge Payment Initiation API
 * API Reference for services
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@saltedge.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.utm.gitfit.model.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * AuthorizePaymentRequestBodyData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-21T15:13:42.040Z[GMT]")
public class AuthorizePaymentRequestBodyData {
  @SerializedName("payment_id")
  private String paymentId = null;

  @SerializedName("query_string")
  private String queryString = null;

  public AuthorizePaymentRequestBodyData paymentId(String paymentId) {
    this.paymentId = paymentId;
    return this;
  }

   /**
   * the &#x60;id&#x60; of the payment that is being authorized
   * @return paymentId
  **/
  @Schema(required = true, description = "the `id` of the payment that is being authorized")
  public String getPaymentId() {
    return paymentId;
  }

  public void setPaymentId(String paymentId) {
    this.paymentId = paymentId;
  }

  public AuthorizePaymentRequestBodyData queryString(String queryString) {
    this.queryString = queryString;
    return this;
  }

   /**
   * all the parameters appended to your &#x60;return_to&#x60; URL upon being redirected from the provider back to your application
   * @return queryString
  **/
  @Schema(required = true, description = "all the parameters appended to your `return_to` URL upon being redirected from the provider back to your application")
  public String getQueryString() {
    return queryString;
  }

  public void setQueryString(String queryString) {
    this.queryString = queryString;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorizePaymentRequestBodyData authorizePaymentRequestBodyData = (AuthorizePaymentRequestBodyData) o;
    return Objects.equals(this.paymentId, authorizePaymentRequestBodyData.paymentId) &&
        Objects.equals(this.queryString, authorizePaymentRequestBodyData.queryString);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentId, queryString);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorizePaymentRequestBodyData {\n");
    
    sb.append("    paymentId: ").append(toIndentedString(paymentId)).append("\n");
    sb.append("    queryString: ").append(toIndentedString(queryString)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
