/*
 * Salt Edge Payment Initiation API
 * API Reference for services
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@saltedge.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.utm.gitfit.model.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * InteractivePaymentRequestBodyData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-21T15:13:42.040Z[GMT]")
public class InteractivePaymentRequestBodyData {
  @SerializedName("interactive_fields")
  private Object interactiveFields = null;

  public InteractivePaymentRequestBodyData interactiveFields(Object interactiveFields) {
    this.interactiveFields = interactiveFields;
    return this;
  }

   /**
   * The credentials object based on the provider’s interactive fields
   * @return interactiveFields
  **/
  @Schema(required = true, description = "The credentials object based on the provider’s interactive fields")
  public Object getInteractiveFields() {
    return interactiveFields;
  }

  public void setInteractiveFields(Object interactiveFields) {
    this.interactiveFields = interactiveFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InteractivePaymentRequestBodyData interactivePaymentRequestBodyData = (InteractivePaymentRequestBodyData) o;
    return Objects.equals(this.interactiveFields, interactivePaymentRequestBodyData.interactiveFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interactiveFields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InteractivePaymentRequestBodyData {\n");
    
    sb.append("    interactiveFields: ").append(toIndentedString(interactiveFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
