/*
 * Salt Edge Payment Initiation API
 * API Reference for services
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@saltedge.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.utm.gitfit.model.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * OauthPaymentRequestBodyData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-21T15:13:42.040Z[GMT]")
public class OauthPaymentRequestBodyData {
  @SerializedName("customer_id")
  private String customerId = null;

  @SerializedName("provider_code")
  private String providerCode = null;

  @SerializedName("payment_attributes")
  private PaymentAttributes paymentAttributes = null;

  @SerializedName("template_identifier")
  private String templateIdentifier = null;

  @SerializedName("return_to")
  private String returnTo = null;

  @SerializedName("locale")
  private String locale = null;

  @SerializedName("custom_fields")
  private Object customFields = null;

  public OauthPaymentRequestBodyData customerId(String customerId) {
    this.customerId = customerId;
    return this;
  }

   /**
   * the &#x60;id&#x60; of the customer received from [customer create](#customers-create)
   * @return customerId
  **/
  @Schema(required = true, description = "the `id` of the customer received from [customer create](#customers-create)")
  public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  public OauthPaymentRequestBodyData providerCode(String providerCode) {
    this.providerCode = providerCode;
    return this;
  }

   /**
   * the code of the desired provider. To access the list of providers that support payments, see [providers list](#providers-list).  Even though the &#x60;provider_code&#x60; is an &#x60;optional&#x60; field, its absence during payment initiation may lead to the following outcomes:   - The end-user may choose a provider that does not support the payment template the client has passed to Salt Edge. This will result in an error.  - The end-user may choose a provider that has additional &#x60;required_payment_fields&#x60;. Absence of required payment attributes during payment initiation will result in an error. 
   * @return providerCode
  **/
  @Schema(required = true, description = "the code of the desired provider. To access the list of providers that support payments, see [providers list](#providers-list).  Even though the `provider_code` is an `optional` field, its absence during payment initiation may lead to the following outcomes:   - The end-user may choose a provider that does not support the payment template the client has passed to Salt Edge. This will result in an error.  - The end-user may choose a provider that has additional `required_payment_fields`. Absence of required payment attributes during payment initiation will result in an error. ")
  public String getProviderCode() {
    return providerCode;
  }

  public void setProviderCode(String providerCode) {
    this.providerCode = providerCode;
  }

  public OauthPaymentRequestBodyData paymentAttributes(PaymentAttributes paymentAttributes) {
    this.paymentAttributes = paymentAttributes;
    return this;
  }

   /**
   * Get paymentAttributes
   * @return paymentAttributes
  **/
  @Schema(required = true, description = "")
  public PaymentAttributes getPaymentAttributes() {
    return paymentAttributes;
  }

  public void setPaymentAttributes(PaymentAttributes paymentAttributes) {
    this.paymentAttributes = paymentAttributes;
  }

  public OauthPaymentRequestBodyData templateIdentifier(String templateIdentifier) {
    this.templateIdentifier = templateIdentifier;
    return this;
  }

   /**
   * payment template identifier received in [show templates](#payment_templates-show)
   * @return templateIdentifier
  **/
  @Schema(required = true, description = "payment template identifier received in [show templates](#payment_templates-show)")
  public String getTemplateIdentifier() {
    return templateIdentifier;
  }

  public void setTemplateIdentifier(String templateIdentifier) {
    this.templateIdentifier = templateIdentifier;
  }

  public OauthPaymentRequestBodyData returnTo(String returnTo) {
    this.returnTo = returnTo;
    return this;
  }

   /**
   * the URL the user will be redirected to after authenticating on the provider&#x27;s side. If you used your own provider keys for the chosen provider, the URL to which the end-user will be redirected will contain a bunch of parameters appended by the provider that you need to send to the [authorize route](#payments-authorize) in order to authorize the payment. 
   * @return returnTo
  **/
  @Schema(required = true, description = "the URL the user will be redirected to after authenticating on the provider's side. If you used your own provider keys for the chosen provider, the URL to which the end-user will be redirected will contain a bunch of parameters appended by the provider that you need to send to the [authorize route](#payments-authorize) in order to authorize the payment. ")
  public String getReturnTo() {
    return returnTo;
  }

  public void setReturnTo(String returnTo) {
    this.returnTo = returnTo;
  }

  public OauthPaymentRequestBodyData locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * the language of the error message in the &lt;a href&#x3D;&#x27;http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes&#x27; target&#x3D;\&quot;_blank\&quot;&gt;ISO 639-1&lt;/a&gt; format. Possible values are: &#x60;bg&#x60;, &#x60;cz&#x60;, &#x60;de&#x60;, &#x60;en&#x60;, &#x60;es-MX&#x60;, &#x60;es&#x60;, &#x60;fi&#x60;, &#x60;fr&#x60;, &#x60;he&#x60;, &#x60;hr&#x60;, &#x60;hu&#x60;, &#x60;it&#x60;, &#x60;nl&#x60;, &#x60;pl&#x60;, &#x60;pt-BR&#x60;, &#x60;pt&#x60;, &#x60;ro&#x60;, &#x60;ru&#x60;, &#x60;si&#x60;, &#x60;sk&#x60;, &#x60;sv&#x60;, &#x60;tr&#x60;, &#x60;uk&#x60;, &#x60;zh-HK&#x60;(Traditional), &#x60;zh&#x60;(Simplified). Defaults to &#x60;en&#x60;.
   * @return locale
  **/
  @Schema(description = "the language of the error message in the <a href='http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes' target=\"_blank\">ISO 639-1</a> format. Possible values are: `bg`, `cz`, `de`, `en`, `es-MX`, `es`, `fi`, `fr`, `he`, `hr`, `hu`, `it`, `nl`, `pl`, `pt-BR`, `pt`, `ro`, `ru`, `si`, `sk`, `sv`, `tr`, `uk`, `zh-HK`(Traditional), `zh`(Simplified). Defaults to `en`.")
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }

  public OauthPaymentRequestBodyData customFields(Object customFields) {
    this.customFields = customFields;
    return this;
  }

   /**
   * a JSON object, which will be sent back on any of your callbacks
   * @return customFields
  **/
  @Schema(description = "a JSON object, which will be sent back on any of your callbacks")
  public Object getCustomFields() {
    return customFields;
  }

  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OauthPaymentRequestBodyData oauthPaymentRequestBodyData = (OauthPaymentRequestBodyData) o;
    return Objects.equals(this.customerId, oauthPaymentRequestBodyData.customerId) &&
        Objects.equals(this.providerCode, oauthPaymentRequestBodyData.providerCode) &&
        Objects.equals(this.paymentAttributes, oauthPaymentRequestBodyData.paymentAttributes) &&
        Objects.equals(this.templateIdentifier, oauthPaymentRequestBodyData.templateIdentifier) &&
        Objects.equals(this.returnTo, oauthPaymentRequestBodyData.returnTo) &&
        Objects.equals(this.locale, oauthPaymentRequestBodyData.locale) &&
        Objects.equals(this.customFields, oauthPaymentRequestBodyData.customFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerId, providerCode, paymentAttributes, templateIdentifier, returnTo, locale, customFields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OauthPaymentRequestBodyData {\n");
    
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    providerCode: ").append(toIndentedString(providerCode)).append("\n");
    sb.append("    paymentAttributes: ").append(toIndentedString(paymentAttributes)).append("\n");
    sb.append("    templateIdentifier: ").append(toIndentedString(templateIdentifier)).append("\n");
    sb.append("    returnTo: ").append(toIndentedString(returnTo)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
