version: "3.5"
services:
  db:
    container_name: mysql_container
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DB: gitfit
      MYSQL_USER: profile
      MYSQL_PASSWORD: profile
      MYSQL_ROOT_PASSWORD: admin
